# name: Tự động Điền Form theo Lịch (Timerun)

# on:
#   schedule:
#     # Chạy 15 phút 1 lần từ 0h đến 16h UTC (7h đến 23h giờ VN)
#     - cron: '*/15 0-16 * * *'
#   workflow_dispatch:  # Cho phép chạy thủ công

# jobs:
#   submit:
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Checkout code
#         # Sử dụng actions/checkout@v4 là phiên bản ổn định
#         uses: actions/checkout@v4
        
#       - name: Cài đặt Python và Dependencies
#         # Kết hợp cài đặt Python và các thư viện cần thiết
#         run: |
#           sudo apt-get update
#           # Cài đặt trình duyệt Chromium (cần thiết cho Selenium Headless)
#           sudo apt-get install -y chromium-browser chromium-chromedriver 
          
#       - name: Set up Python
#         uses: actions/setup-python@v5 # Dùng phiên bản mới nhất
#         with:
#           python-version: '3.10'
          
#       - name: Install Python dependencies
#         run: |
#           pip install -r requirements.txt
          
#       - name: Thực thi Script Điều phối (timerun.py)
#         # timerun.py sẽ gọi khaosatcheogithub.py và chờ nó hoàn thành
#         run: python timerun.py
        
#       - name: Commit và Push file time.csv đã cập nhật
#         # Dùng action chuyên dụng để xử lý việc commit file an toàn hơn.
#         # Commit chỉ file time.csv vì file này chứa trạng thái (dòng đã xóa/còn lại).
#         uses: stefanzweifel/git-auto-commit-action@v5
#         with:
#           commit_message: "Auto: Cập nhật time.csv sau khi điền form thành công."
#           files: time.csv
#           # Không cần index.txt vì đã loại bỏ logic trong Python
